In [ ]:
# Load in libraries and match data

import json
import pandas as pd

with open("Single Match Data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,shot.one_on_one,foul_committed.advantage,foul_won.advantage,clearance.aerial_won,pass.deflected,pass.no_touch,foul_committed.type.id,foul_committed.type.name,pass.straight,pass.goal_assist
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0300039d-150d-41e4-b29a-76602ef002e6,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,491e8901-7630-4cc8-b57b-937dddff2eaa,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,5,1,00:00:00.575,0,0,2,2.015669,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df. head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,shot.one_on_one,foul_committed.advantage,foul_won.advantage,clearance.aerial_won,pass.deflected,pass.no_touch,foul_committed.type.id,foul_committed.type.name,pass.straight,pass.goal_assist
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0300039d-150d-41e4-b29a-76602ef002e6,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,491e8901-7630-4cc8-b57b-937dddff2eaa,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,5,1,00:00:00.575,0,0,2,2.015669,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
for col in df.columns:
    print(col)

id
index
period
timestamp
minute
second
possession
duration
type.id
type.name
possession_team.id
possession_team.name
play_pattern.id
play_pattern.name
team.id
team.name
tactics.formation
tactics.lineup
related_events
location
player.id
player.name
position.id
position.name
pass.recipient.id
pass.recipient.name
pass.length
pass.angle
pass.height.id
pass.height.name
pass.end_location
pass.body_part.id
pass.body_part.name
pass.type.id
pass.type.name
carry.end_location
pass.switch
pass.outcome.id
pass.outcome.name
ball_receipt.outcome.id
ball_receipt.outcome.name
under_pressure
duel.type.id
duel.type.name
pass.aerial_won
counterpress
interception.outcome.id
interception.outcome.name
off_camera
ball_recovery.recovery_failure
pass.assisted_shot_id
pass.shot_assist
shot.statsbomb_xg
shot.end_location
shot.key_pass_id
shot.outcome.id
shot.outcome.name
shot.first_time
shot.technique.id
shot.technique.name
shot.body_part.id
shot.body_part.name
shot.type.id
shot.type.name
shot.freeze_frame
goalkeeper.end_location
goalkeeper.type.id
goalkeeper.type.name
goalkeeper.position.id
goalkeeper.position.name
pass.cross
goalkeeper.outcome.id
goalkeeper.outcome.name
clearance.left_foot
clearance.body_part.id
clearance.body_part.name
block.deflection
duel.outcome.id
duel.outcome.name
dribble.nutmeg
dribble.outcome.id
dribble.outcome.name
foul_committed.offensive
foul_committed.card.id
foul_committed.card.name
foul_won.defensive
pass.through_ball
pass.technique.id
pass.technique.name
out
clearance.right_foot
pass.inswinging
goalkeeper.technique.id
goalkeeper.technique.name
goalkeeper.body_part.id
goalkeeper.body_part.name
clearance.head
shot.aerial_won
miscontrol.aerial_won
dribble.overrun
pass.miscommunication
block.offensive
bad_behaviour.card.id
bad_behaviour.card.name
substitution.outcome.id
substitution.outcome.name
substitution.replacement.id
substitution.replacement.name
pass.cut_back
shot.one_on_one
foul_committed.advantage
foul_won.advantage
clearance.aerial_won
pass.deflected
pass.no_touch
foul_committed.type.id
foul_committed.type.name
pass.straight
pass.goal_assist